In [1]:
name=input("enter your name:")
address=input("enter your address:")
email=input("enter your email:")
phone_number=input("enter your phone number:")
print("Name:",name)
print("Address:",address)
print("Email:",email)
print("Phone number:",phone_number)

enter your name: Vaishnavi
enter your address: cmr technical campus
enter your email: 247r1a6680@cmrtc.ac.in
enter your phone number: 9182986020


Name: Vaishnavi
Address: cmr technical campus
Email: 247r1a6680@cmrtc.ac.in
Phone number: 9182986020


In [19]:
num=int(input("Please Enter the Number of Rows:"))
for i in range(1,num+1):
        for j in range(1,i+1):
            print(num,end=' ')
        num=num-1
        print()



Please Enter the Number of Rows: 5


5 
4 4 
3 3 3 
2 2 2 2 
1 1 1 1 1 


In [14]:
ch-input("Please enter any character:\t")
if(cb>='A' and ch <= 'Z'):
    print(ch,"is an Upper case character");
elif(ch>='a' anc ch<='z'):
    print(ch,"is an Lower case character")
elif(ch>

1
2
3


In [1]:
a="hello vaishnavi"
for i in a:
    print(i)

h
e
l
l
o
 
v
a
i
s
h
n
a
v
i


In [4]:
list=[1,2,3,4,5,6,7,8,9,10]
n=int(input("enter any number:"))
for i in list:
    c=n*i
    print(n,'*',i,'=',c)
    

enter any number: 50


50 * 1 = 50
50 * 2 = 100
50 * 3 = 150
50 * 4 = 200
50 * 5 = 250
50 * 6 = 300
50 * 7 = 350
50 * 8 = 400
50 * 9 = 450
50 * 10 = 500


In [5]:
list=[11,22,33,44,55,66,77]
sum = 0
for i in list:
    sum = sum + i
print("The sum is : ",sum)

The sum is :  308


In [10]:
for i in range(0,10,2):
    print(i)


0
2
4
6
8


In [20]:
rows=int(input("enter the no of rows:"))
for i in range(1,rows+1):
    for j in range(1,i+1):
        print(j,end=' ')
    print()

enter the no of rows: 6


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 


In [21]:
rows=int(input("enter the no of rows:"))
for i in range(1,rows+1):
    for j in range(i):
        print(i,end=' ')
    print()

enter the no of rows: 6


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 
6 6 6 6 6 6 


In [23]:
count = 0
while count<4:
    print("hello python")
    count = count+1

hello python
hello python
hello python
hello python


In [32]:
for i in range(1,5,5):
    print("yes")
else:
    print("no")


yes
no


In [39]:
str = "python"
for i in str:
    if i=='o':
        continue;
    print(i)

p
y
t
h
n


In [42]:
for i in range(1,11):
    if i==5:
        continue;
    print(i)

1
2
3
4
6
7
8
9
10


In [ ]:
i=1
while i<11:
    if i == 5:
        continue
    print(i)
    i = i + 1
    

In [12]:
ch=input("please enter any character:")

if(ch>='A' and ch<='Z'):
    print(ch,"is an upper case character")
elif(ch>='a' and ch<='z'):
    print(ch,"is an lower case character")
elif(ch>='0' and ch<='9'):
    print(ch,"is a digit")
else:
    print("it is a special character")

please enter any character: %


it is a special character


In [13]:
nterms=int(input("how many terms:"))
n1,n2=0,1
count=0
if nterms<=0:
    print("please enter a positive interger")
elif nterms==1:
    print("fibonacci sequence upto",nterms,":")
    print(n1)
else:
    print("fibonacci series:")
    while count<nterms:
        print(n1)
        nth=n1+n2
        n1=n2
        n2=nth
        count+=1
    


how many terms: 10


fibonacci series:
0
1
1
2
3
5
8
13
21
34


In [8]:
lower_value=int(input("enter lower range value:"))
upper_value=int(input("enter upper range value:"))
print("the prime numbers in the range are:",lower_value,'and',upper_value)
for number in range(lower_value,upper_value+1):
    if number>1:
        for i in range(2,number):
            if (number%i)==0:
                break
        else:
            print(number)

enter lower range value: 2
enter upper range value: 10


the prime numbers in the range are: 2 and 10
2
3
5
7


In [10]:
x=10
y=0
print("x/y value is:")
assert y!=0, " divide by 0 error"
print(x/y)

x/y value is:


AssertionError:  divide by 0 error

In [12]:
def sum():
    a=101
    b=200
    c=a+b
    return c
result=sum()
print("the sum of a and b is:",result)

the sum of a and b is: 301


In [13]:
def area():
    b=10
    h=15
    c=0.5*b*h
    return c
result=area()
print("area of triangle is:",result)

area of triangle is: 75.0


In [14]:
def area():
    r=4
    area=3.14*r*r
    return area
result=area()
print("area of circle is:",result)

area of circle is: 50.24


In [1]:
i=1
while i<=4:
    print(i)
    i+=1

1
2
3
4


In [5]:
import numpy as np
my_list=[];
list_length=int(input("enter no of list elements:"))
for i in range(list_length):
    st=int(input("enter element:"))
    my_list.append(st)
print(my_list)
print(type(my_list))


enter no of list elements: 3
enter element: 1
enter element: 2
enter element: 3


[1, 2, 3]
<class 'list'>


In [10]:
import numpy as np
my_list=[10,20,30,40]
my_tuple=[60,33,4,5]
array_from_list=np.array(my_list)
array_from_tuple=np.array(my_tuple)
print("List:",my_list)
print("array from list:",array_from_list)
print(type(array_from_list))
print("tuple:",my_tuple)
print("array from typle:",array_from_tuple)

List: [10, 20, 30, 40]
array from list: [10 20 30 40]
<class 'numpy.ndarray'>
tuple: [60, 33, 4, 5]
array from typle: [60 33  4  5]


In [14]:
import numpy as np
a=np.array([-1,-2,1,4,100,5])
print("the array:",a)
print("min element is :",a.min())
print("max element is :",a.max())
print("sum of elements in array is: ",a.sum())

the array: [ -1  -2   1   4 100   5]
min element is : -2
max element is : 100
sum of elements in array is:  107


In [20]:
import numpy as np
a=np.array([[1,2,30],[10,15,4]])
print("the array:'",a)
print("the max elements of coulumn:",a.max(axis=0))
print("the min elements of row:",a.min(axis=1))

the array:' [[ 1  2 30]
 [10 15  4]]
the max elements of coulumn: [10 15 30]
the min elements of row: [1 4]


In [23]:
import numpy as np
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
b=a.flatten()
print(b)
x=a.flatten('F')
print(x)

[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
import numpy as np
b=np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
import numpy as np
b=np.ones(5,dtype=np.int32)
print(b)

[1 1 1 1 1]


In [31]:
import numpy as np
b=np.random.rand(2,3)
print(b)

[[0.51840355 0.89631439 0.68323377]
 [0.12762396 0.62218636 0.12257233]]


In [32]:
a=np.array([[2,4],[5,-6]])
b=np.array([[9,-3],[3,6]])
c=a+b
print(c)

[[11  1]
 [ 8  0]]
